# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Paulo/Desktop/EE_Masters/EC/NullShift/NullShift.srcs/sources_1/bd/fdm/ip/fdm_clk_wiz_7/fdm_clk_wiz_7.xci
# IP: The module: 'fdm_clk_wiz_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Paulo/Desktop/EE_Masters/EC/NullShift/NullShift.gen/sources_1/bd/fdm/ip/fdm_clk_wiz_7/fdm_clk_wiz_7_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdm_clk_wiz_7'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Paulo/Desktop/EE_Masters/EC/NullShift/NullShift.gen/sources_1/bd/fdm/ip/fdm_clk_wiz_7/fdm_clk_wiz_7.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdm_clk_wiz_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Paulo/Desktop/EE_Masters/EC/NullShift/NullShift.gen/sources_1/bd/fdm/ip/fdm_clk_wiz_7/fdm_clk_wiz_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdm_clk_wiz_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Paulo/Desktop/EE_Masters/EC/NullShift/NullShift.srcs/sources_1/bd/fdm/ip/fdm_clk_wiz_7/fdm_clk_wiz_7.xci
# IP: The module: 'fdm_clk_wiz_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Paulo/Desktop/EE_Masters/EC/NullShift/NullShift.gen/sources_1/bd/fdm/ip/fdm_clk_wiz_7/fdm_clk_wiz_7_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdm_clk_wiz_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Paulo/Desktop/EE_Masters/EC/NullShift/NullShift.gen/sources_1/bd/fdm/ip/fdm_clk_wiz_7/fdm_clk_wiz_7.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdm_clk_wiz_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Paulo/Desktop/EE_Masters/EC/NullShift/NullShift.gen/sources_1/bd/fdm/ip/fdm_clk_wiz_7/fdm_clk_wiz_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdm_clk_wiz_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
