set_property SRC_FILE_INFO {cfile:C:/Users/Paulo/Desktop/EE_Masters/EC/NullShiftV2/NullShiftV2.srcs/constrs_1/imports/NullShift/pauloportas.xdc rfile:../../../NullShiftV2.srcs/constrs_1/imports/NullShift/pauloportas.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports sys_clock]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports reset]
