# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Paulo/Desktop/EE_Masters/EC/NullShiftV2/NullShiftV2.srcs/sources_1/bd/fdm/ip/fdm_blk_mem_gen_0_0/fdm_blk_mem_gen_0_0.xci
# IP: The module: 'fdm_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Paulo/Desktop/EE_Masters/EC/NullShiftV2/NullShiftV2.gen/sources_1/bd/fdm/ip/fdm_blk_mem_gen_0_0/fdm_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdm_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Paulo/Desktop/EE_Masters/EC/NullShiftV2/NullShiftV2.srcs/sources_1/bd/fdm/ip/fdm_blk_mem_gen_0_0/fdm_blk_mem_gen_0_0.xci
# IP: The module: 'fdm_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Paulo/Desktop/EE_Masters/EC/NullShiftV2/NullShiftV2.gen/sources_1/bd/fdm/ip/fdm_blk_mem_gen_0_0/fdm_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdm_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
