# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/NullShift/pauloportas.xdc

# Block Designs: bd/fdm/fdm.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm || ORIG_REF_NAME==fdm} -quiet] -quiet

# IP: bd/fdm/ip/fdm_blk_mem_gen_0_0/fdm_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_blk_mem_gen_0_0 || ORIG_REF_NAME==fdm_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/fdm/ip/fdm_blk_mem_gen_0_1/fdm_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_blk_mem_gen_0_1 || ORIG_REF_NAME==fdm_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/fdm/ip/fdm_ila_0_0/fdm_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_ila_0_0 || ORIG_REF_NAME==fdm_ila_0_0} -quiet] -quiet

# IP: bd/fdm/ip/fdm_clk_wiz_0_0/fdm_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_clk_wiz_0_0 || ORIG_REF_NAME==fdm_clk_wiz_0_0} -quiet] -quiet

# IP: bd/fdm/ip/fdm_dds_compiler_0_0/fdm_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_dds_compiler_0_0 || ORIG_REF_NAME==fdm_dds_compiler_0_0} -quiet] -quiet

# IP: bd/fdm/ip/fdm_mult_gen_0_0/fdm_mult_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_mult_gen_0_0 || ORIG_REF_NAME==fdm_mult_gen_0_0} -quiet] -quiet

# IP: bd/fdm/ip/fdm_mult_gen_0_1/fdm_mult_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_mult_gen_0_1 || ORIG_REF_NAME==fdm_mult_gen_0_1} -quiet] -quiet

# IP: bd/fdm/ip/fdm_xlconstant_0_0/fdm_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_xlconstant_0_0 || ORIG_REF_NAME==fdm_xlconstant_0_0} -quiet] -quiet

# IP: bd/fdm/ip/fdm_bin_data_stream_1_0/fdm_bin_data_stream_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_bin_data_stream_1_0 || ORIG_REF_NAME==fdm_bin_data_stream_1_0} -quiet] -quiet

# IP: bd/fdm/ip/fdm_ask_mapper_0/fdm_ask_mapper_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_ask_mapper_0 || ORIG_REF_NAME==fdm_ask_mapper_0} -quiet] -quiet

# IP: bd/fdm/ip/fdm_ask_modulator_0/fdm_ask_modulator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_ask_modulator_0 || ORIG_REF_NAME==fdm_ask_modulator_0} -quiet] -quiet

# IP: bd/fdm/ip/fdm_mult_gen_0_2/fdm_mult_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_mult_gen_0_2 || ORIG_REF_NAME==fdm_mult_gen_0_2} -quiet] -quiet

# IP: bd/fdm/ip/fdm_gain_ask_0/fdm_gain_ask_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_gain_ask_0 || ORIG_REF_NAME==fdm_gain_ask_0} -quiet] -quiet

# IP: bd/fdm/ip/fdm_mult_gen_1_0/fdm_mult_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_mult_gen_1_0 || ORIG_REF_NAME==fdm_mult_gen_1_0} -quiet] -quiet

# IP: bd/fdm/ip/fdm_c_addsub_0_0/fdm_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_c_addsub_0_0 || ORIG_REF_NAME==fdm_c_addsub_0_0} -quiet] -quiet

# IP: bd/fdm/ip/fdm_fir_compiler_0_0/fdm_fir_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_fir_compiler_0_0 || ORIG_REF_NAME==fdm_fir_compiler_0_0} -quiet] -quiet

# IP: bd/fdm/ip/fdm_c_shift_ram_0_0/fdm_c_shift_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdm_c_shift_ram_0_0 || ORIG_REF_NAME==fdm_c_shift_ram_0_0} -quiet] -quiet

# XDC: c:/Users/Paulo/Desktop/EE_Masters/EC/NullShiftV2/NullShiftV2.gen/sources_1/bd/fdm/fdm_ooc.xdc
